[package]
name = "queue"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
sqlx = { version = "0.8", features = [ "runtime-tokio" ] }
tokio = { version = "1.39.2", features = ["full"] }
